Repository MaFeLP/TransitTrail, pull requests merged in 2023-06, with the labels that each got.

#56 🆙 Updated dependencies
  package.json
  pnpm-lock.yaml
  src-tauri/Cargo.lock
  transit-api-client/Cargo.toml
Labels: dependency

#58 🐞 Fixed a bug in the release CI
  .github/workflows/upload-release.yml
Labels: bug, CI/CD

#61 🗺️ Trip planner
  .github/workflows/upload-release.yml
  src-tauri/Cargo.lock
  src-tauri/src/main.rs
  src-tauri/src/settings.rs
  src-tauri/src/stop_info.rs
  src-tauri/src/trip_planner.rs
  src/lib/SideBar.svelte
  src/lib/components/LocationSearch.svelte
  src/lib/components/TransitPlan.svelte
  src/lib/components/TripLocation.svelte
  src/lib/components/walking.svg
  src/lib/pages/Settings.svelte
  src/lib/pages/TripPlanner.svelte
  src/styles/main.sass
  src/types/common.ts
  src/types/filters.ts
  src/types/index.ts
  src/types/routes.ts
  src/types/service_advisories.ts
  src/types/settings.d.ts
  src/types/settings.ts
  src/types/stops.ts
  src/types/trip_planner.ts
  transit-api-client/Cargo.toml
  transit-api-client/src/endpoints/locations.rs
  transit-api-client/src/endpoints/stops.rs
  transit-api-client/src/endpoints/street.rs
  transit-api-client/src/endpoints/trip_planner.rs
  transit-api-client/src/filters.rs
  transit-api-client/src/structs/common.rs
  transit-api-client/src/structs/stops.rs
  transit-api-client/src/structs/trip_planner/mod.rs
  transit-api-client/src/structs/trip_planner/segment.rs
Labels: enhancement, frontend, backend, transit API

#71 Homepage
  README.md
  src-tauri/src/main.rs
  src/lib/pages/Home.svelte
  src/lib/pages/Settings.svelte
Labels: documentation, frontend

#72 🆙 Updated dependencies
  Cargo.lock
  package.json
  pnpm-lock.yaml
Labels: dependency

#70 Added Copyright
  .gitmodules
  src-tauri/src/main.rs
  src-tauri/src/service_advisory.rs
  src-tauri/src/settings.rs
  src-tauri/src/stop_info.rs
  src-tauri/src/stop_schedules.rs
  src-tauri/src/trip_planner.rs
  src/App.svelte
  src/lib/SideBar.svelte
  src/lib/components/GoogleTransitPlan.svelte
  src/lib/components/LocationSearch.svelte
  src/lib/components/TransitPlan.svelte
  src/lib/components/TripLocation.svelte
  src/lib/pages/Home.svelte
  src/lib/pages/NearbyStops.svelte
  src/lib/pages/ServiceAdvisories.svelte
  src/lib/pages/Settings.svelte
  src/lib/pages/Stops.svelte
  src/lib/pages/TripPlanner.svelte
  src/main.ts
  src/styles/main.sass
  src/styles/route-badge-label.sass
  src/styles/service-advisories.sass
  src/styles/stops.sass
  src/styles/variables.sass
  src/types/common.ts
  src/types/filters.ts
  src/types/index.ts
  src/types/routes.ts
  src/types/service_advisories.ts
  src/types/settings.ts
  src/types/stops.ts
  src/types/trip_planner.ts
  src/util.ts
  src/vite-env.d.ts
  transit-api-client/src/endpoints/destinations.rs
  transit-api-client/src/endpoints/locations.rs
  transit-api-client/src/endpoints/mod.rs
  transit-api-client/src/endpoints/routes.rs
  transit-api-client/src/endpoints/service_advisories.rs
  transit-api-client/src/endpoints/stops.rs
  transit-api-client/src/endpoints/street.rs
  transit-api-client/src/endpoints/trip_planner.rs
  transit-api-client/src/endpoints/variants.rs
  transit-api-client/src/filters.rs
  transit-api-client/src/lib.rs
  transit-api-client/src/prelude.rs
  transit-api-client/src/structs/common.rs
  transit-api-client/src/structs/destinations.rs
  transit-api-client/src/structs/mod.rs
  transit-api-client/src/structs/routes.rs
  transit-api-client/src/structs/service_advisories.rs
  transit-api-client/src/structs/stops.rs
  transit-api-client/src/structs/trip_planner/mod.rs
  transit-api-client/src/structs/trip_planner/segment.rs
Labels: documentation
